# Flake outputs entry point
# This file is referenced by the auto-generated flake.nix
inputs:
let
  inherit (inputs)
    nixpkgs
    flake-parts
    imp
    ;
in
flake-parts.lib.mkFlake { inherit inputs; } {
  imports = [
    imp.flakeModules.default
  ];

  systems = import inputs.systems;

  # imp configuration
  imp = {
    bundles.src = ../bundles;

    # Extra args available in all output files
    args = {
      inherit nixpkgs;
      rootSrc = ../..;
    };

    # Disable exports (not used in this project)
    exports.enable = false;

    # Auto-generate default devShell composing all bundle devShells
    impShell.enable = true;

    # Auto-generate flake.nix from __inputs declarations
    flakeFile = {
      enable = true;
      coreInputs = import ./inputs.nix;
      description = "Query Rust docs and crate API from the command line";
      outputsFile = "./nix/flake";
      header = ''
        # Auto-generated by imp - DO NOT EDIT
        # Regenerate with: nix run .#imp-flake
      '';
    };
  };
}
